

//---------------------------------------------------------------------
### Get Home Page
//---------------------------------------------------------------------

GET http://localhost:4200 HTTP/1.1


//---------------------------------------------------------------------
### Auth Login
//---------------------------------------------------------------------

POST http://localhost:4200/auth/login HTTP/1.1
content-type: application/json

{
    "user_email": "admin@server",
    "password": "password"
}


//---------------------------------------------------------------------
### Auth Logout
//---------------------------------------------------------------------

POST http://localhost:4200/auth/logout HTTP/1.1
content-type: application/json

{
    "user_email": "admin@server"
}


//---------------------------------------------------------------------
### Server Signup
//---------------------------------------------------------------------

POST http://localhost:4200/Authentication/Signup HTTP/1.1
content-type: application/json

{
    "user_email": "admin@server",
    "password": "password",
    "user_name": "Administrator"
}


//---------------------------------------------------------------------
### Server Login
//---------------------------------------------------------------------

POST http://localhost:4200/Authentication/Login HTTP/1.1
content-type: application/json

{
    "user_email": "admin@server",
    "password": "password"
}


//---------------------------------------------------------------------
### Connect Session
//---------------------------------------------------------------------

POST http://localhost:4200/Authentication/ConnectSession HTTP/1.1
content-type: application/json

{
    "session_token": "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..a8JeC_wKErIW-a-1.p0dKTYxF0hYwMr8NdiIYADfNrHafqMqDm9IPbwvz3b-yD2lWhnM_8dP0xKEN6L30GS752j2Z2NAq1sltEFB4UF29TyFwzeLMb1BJv0QJoqw.gUnIyQ_XY7l-duAzcqTgFA"
}


//---------------------------------------------------------------------
### Server Logout
//---------------------------------------------------------------------

POST http://localhost:4200/Authentication/Logout HTTP/1.1
content-type: application/json

{
    "user_email": "admin@server"
}


//---------------------------------------------------------------------
### ServerAccounts.StorageCount
//---------------------------------------------------------------------

GET http://localhost:4200/ServerAccounts/StorageCount HTTP/1.1


//---------------------------------------------------------------------
### Maths.Divide
//---------------------------------------------------------------------

GET http://localhost:4200/Maths/Divide HTTP/1.1
content-type: application/json

{
    "operand_a": 3,
    "operand_b": 4
}

